import type { ZoteroCitationItem, ZoteroCitationResponse } from "./types.ts";

export const BIBTEX_EXPORT_MARKER = "% Generated by Local Zotero Mirror";

export interface CitationExportResult {
  text: string;
  count: number;
  warnings: string[];
  missingCitekeys: string[];
  skippedCitekeys: string[];
}

export function formatApaReferenceList(response: ZoteroCitationResponse | null): CitationExportResult {
  if (!response) {
    return emptyCitationExport(["当前文件没有引用文献。"]);
  }

  const references = uniqueStrings(response.bibliography.map((entry) => entry.trim()).filter(Boolean));
  const warnings = citationResponseWarnings(response);
  if (references.length === 0) {
    warnings.push("当前引用没有可复制的 APA references。");
  }

  return {
    text: references.length > 0 ? `${references.join("\n\n")}\n` : "",
    count: references.length,
    warnings,
    missingCitekeys: response.missingCitekeys,
    skippedCitekeys: []
  };
}

export function formatBibtexEntries(response: ZoteroCitationResponse | null): CitationExportResult {
  if (!response) {
    return emptyCitationExport(["当前文件没有引用文献。"]);
  }

  const seen = new Set<string>();
  const entries: string[] = [];
  const skippedCitekeys: string[] = [];

  for (const entry of response.entries) {
    const bibtex = entry.citation.bibtex?.trim();
    if (!bibtex) {
      skippedCitekeys.push(entry.citekey || entry.citation.citekey || entry.itemKey);
      continue;
    }
    const key = bibtexDedupeKey(entry, bibtex);
    if (seen.has(key)) continue;
    seen.add(key);
    entries.push(bibtex);
  }

  const warnings = citationResponseWarnings(response);
  if (skippedCitekeys.length > 0) {
    warnings.push(`缺少 BibTeX：${uniqueStrings(skippedCitekeys).join(", ")}`);
  }
  if (entries.length === 0) {
    warnings.push("当前引用没有可复制的 BibTeX entries。");
  }

  return {
    text: entries.length > 0 ? `${entries.join("\n\n")}\n` : "",
    count: entries.length,
    warnings,
    missingCitekeys: response.missingCitekeys,
    skippedCitekeys: uniqueStrings(skippedCitekeys)
  };
}

export function buildBibtexExportFile(args: {
  sourcePath: string;
  generatedAt: string;
  response: ZoteroCitationResponse | null;
}): CitationExportResult {
  const formatted = formatBibtexEntries(args.response);
  if (!formatted.text) return formatted;

  const header = [
    BIBTEX_EXPORT_MARKER,
    `% Source: ${args.sourcePath}`,
    `% Generated at: ${args.generatedAt}`,
    `% Entries: ${formatted.count}`
  ].join("\n");

  return {
    ...formatted,
    text: `${header}\n\n${formatted.text}`
  };
}

function emptyCitationExport(warnings: string[]): CitationExportResult {
  return {
    text: "",
    count: 0,
    warnings,
    missingCitekeys: [],
    skippedCitekeys: []
  };
}

function citationResponseWarnings(response: ZoteroCitationResponse): string[] {
  const warnings: string[] = [];
  if (response.missingCitekeys.length > 0) {
    warnings.push(`缺失 citekey：${response.missingCitekeys.join(", ")}`);
  }
  if (response.error) {
    warnings.push(response.error);
  }
  return warnings;
}

function bibtexDedupeKey(entry: ZoteroCitationItem, bibtex: string): string {
  const entryKey = bibtex.match(/^@\w+\s*\{\s*([^,\s]+)\s*,/i)?.[1];
  return entryKey || entry.itemKey || entry.citekey || bibtex;
}

function uniqueStrings(values: string[]): string[] {
  const seen = new Set<string>();
  const result: string[] = [];
  for (const value of values) {
    if (seen.has(value)) continue;
    seen.add(value);
    result.push(value);
  }
  return result;
}
